---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: ストレージ データを移行する場合、ストレージ バックエンドは REST API を使用して手動でオンボードされます。  VASA プロバイダー データを移行する場合、データは既存の Derby データベースからエクスポートされ、MongoDB データベースにインポートされます。 
---
= VASA プロバイダーを移行し、SRA を更新する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このセクションの手順に従って、VASA プロバイダーをONTAP tools for VMware vSphere 9.xx からONTAP tools for VMware vSphere 10.4 に移行し、VMware Live Site Recovery アプライアンス上のストレージ レプリケーション アダプタ (SRA) を更新します。



== VASAプロバイダーの移行手順

. ONTAP tools for VMware vSphereで Derby PORT 1527 を有効にするには、root ユーザーを有効にし、SSH 経由で CLI にログインします。次に、次のコマンドを実行します。
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. ONTAP tools for VMware vSphereをデプロイします。
. 移行する vCenter Server インスタンスを、 ONTAP tools for VMware vSphereに追加します。参照link:../configure/add-vcenter.html["vCenter Serverインスタンスを追加する"]詳細についてはこちらをご覧ください。
. ONTAPツールプラグインのvCenter Server APIからストレージバックエンドをローカルにオンボードします。link:../configure/add-storage-backend.html["vSphere クライアント インターフェイスを使用してストレージ バックエンドを追加する"]詳細についてはこちらをご覧ください。
. REST API リクエストを認証するためのアクセス トークンを取得します。次の例を使用して、変数を環境固有の値に置き換えます。
+
+



[listing]
----
curl --request POST \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/login” \
--header "Content-Type: application/json" \
--header "Accept: */*" \
-d "{"username": "$MYUSER", "password": "$MYPASSWORD"}"
----
レスポンスで返されたアクセス トークンをコピーして保存します。。移行するには、Swagger または Postman から次の API を発行します。

+

[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
+ この URL から Swagger にアクセスできます。 `\https://$FQDN_IP_PORT/` 、 例えば： `\https://10.67.25.33:8443/` 。

+

[]
====
*HTTPメソッドとエンドポイント*

このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

|===


| *HTTPメソッド* | *パス* 


| POST | /api/v1 
|===
*処理タイプ*

非同期

*カールの例*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
--header 'x-auth: <auth_token>' \
--header 'Content-Type: application/json' \
--data '{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "******"
  },
  "database_password": "******"
}'
----
他のリリース移行のリクエスト本文:

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
*JSON出力例*

システムはジョブ オブジェクトを返します。次のステップで使用するためにジョブ識別子を保存します。

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
. ステータスを確認するには、Swagger で次の URI を使用します。
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<migration_id>?includeSubJobsAndTasks=true`
----
+
ジョブが完了したら、ジョブ応答の移行レポートを確認します。

. ONTAP tools for VMware vSphereをvCenter Server に追加します。
. VASA プロバイダーをONTAP tools for VMware vSphereに登録します。手順については、link:../configure/registration-process.html["VASAプロバイダーを登録する"] 。
. 登録後、vSphere Client の *ストレージ プロバイダー* で VASA プロバイダーの名前とステータスを確認します。VASA プロバイダーがオンラインになり、登録が成功したことが確認されます。
. link:../manage/enable-services.html["VASA Provider の有効化"]ONTAP tools for VMware vSphereのサービス。
. 次の手順に従って、 ONTAP tools for VMware vSphereを停止します。
+
.. ONTAPツール 9.x で、Web コンソールを開きます。
.. メンテナンス コンソールにアクセスします。
.. 入力 `1`*アプリケーション構成*メニューを選択します。
.. 入力 `5`VASA プロバイダーおよび SRA サービスを停止します。
.. vSphere Client で、*インベントリ* > *ストレージ プロバイダー* に移動します。
.. ストレージ バックエンドからONTAPツール 9.x VASA プロバイダーを選択し、[削除] をクリックします。
+
古いVASAプロバイダが停止すると、vCenter ServerはONTAP tools for VMware vSphereにフェイルオーバーします。すべてのデータストアと仮想マシンはONTAP tools for VMware vSphereからアクセス可能になり、サービスが提供されます。



. 移行された NFS および VMFS データストアは、データストア検出ジョブの完了後にONTAP tools for VMware vSphereに表示されます。この処理には最大 30 分かかる場合があります。概要ページで可視性を確認します。
. Swagger または Postman で次の API を使用してパッチの移行を実行します。
+
[]
====
*HTTPメソッドとエンドポイント*

このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

|===


| *HTTPメソッド* | *パス* 


| PATCH | /api/v1 
|===
*処理タイプ*

非同期

Swagger では次の URI を使用します。

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*カールの例*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
*JSON出力例*

ジョブ オブジェクトが返されます。次のステップで使用するためにジョブ ID を保存する必要があります。

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+
パッチ操作のリクエスト本体は空です。




NOTE: UUID は、移行後 API への応答として返される移行 UUID です。

パッチ移行 API を実行すると、すべての VM がストレージ ポリシーに準拠します。

.次の手順
移行を完了し、 ONTAPツール 10.4 を vCenter Server に登録したら、次の手順を実行します。

* *検出* が完了するまで待機します。完了すると、システムはすべてのホスト上の証明書を自動的に更新します。
* データストアおよび仮想マシンの操作を開始する前に待機します。待機時間は、ホスト、データストア、および仮想マシンの数によって異なります。待たないと、時々失敗が発生する可能性があります。


アップグレード後、仮想マシンのコンプライアンス状態が古くなっている場合、次の手順に従ってストレージ ポリシーを再適用します。

. データストアに移動し、*概要* > *VM ストレージ ポリシー* を選択します。
+
システムは、*VM ストレージ ポリシー コンプライアンス* のコンプライアンス ステータスを *古い* と表示します。

. ストレージ VM ポリシーと対応する VM を選択します。
. *適用*を選択します。
+
*VM ストレージ ポリシー コンプライアンス* のコンプライアンス ステータスは、準拠として表示されます。関連情報

+
** link:../concepts/rbac-learn-about.html["ONTAP tools for VMware vSphereについて学ぶ"]
** link:../upgrade/upgrade-ontap-tools.html["ONTAP tools for VMware vSphereから 10.4 へのアップグレード"]






== ストレージレプリケーションアダプタ(SRA)を更新する手順

.開始する前に
リカバリプランにおいて、保護サイトとは仮想マシンが現在実行されている場所を指し、リカバリサイトとは仮想マシンがリカバリされる場所を指します。SRMインターフェースには、リカバリプランの状態と、保護サイトとリカバリサイトの詳細が表示されます。リカバリプランでは、「*CleanupP*」ボタンと「*Reprotect*」ボタンは無効になっていますが、「TEST」ボタンと「RUN」ボタンは有効なままです。これは、サイトがデータリカバリの準備ができていることを示します。SRAを移行する前に、一方のサイトが保護状態、もう一方のサイトがリカバリ状態であることを確認してください。


NOTE: フェイルオーバーは完了しているが再保護が保留中の場合は、移行を開始しないでください。移行を続行する前に、再保護プロセスが完了していることを確認してください。テスト フェイルオーバーが進行中の場合は、テスト フェイルオーバーをクリーンアップして移行を開始します。

. VMware Site Recovery で VMware vSphere 9.xx 用のONTAPツール SRA アダプタを削除するには、次の手順に従います。
+
.. VMware Live Site Recovery 構成管理ページに移動します
.. *ストレージ レプリケーション アダプタ* セクションに移動します。
.. 省略記号メニューから*構成のリセット*を選択します。
.. 省略記号メニューから*削除*を選択します。


. 保護サイトと回復サイトの両方でこれらの手順を実行します。
+
.. link:../manage/enable-services.html["ONTAP tools for VMware vSphereを有効にする"]
.. ONTAP tools for VMware vSphereを以下の手順でインストールします。link:../protect/configure-on-srm-appliance.html["VMware Live Site RecoveryアプライアンスでSRAを構成する"] 。
.. VMware Live Site Recovery ユーザー インターフェイス ページで、*アレイの検出* および *デバイスの検出* 操作を実行し、デバイスが移行前と同じように表示されていることを確認します。



