---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: ストレージ データを移行する場合、ストレージ バックエンドは REST API を使用して手動でオンボードされます。  VASA プロバイダー データを移行する場合、データは既存の Derby データベースからエクスポートされ、MongoDB データベースにインポートされます。 
---
= VASA プロバイダーを移行し、SRA を更新する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== VASAプロバイダーの移行手順

. ONTAP tools for VMware vSphereで Derby PORT 1527 を有効にするには、root ユーザーを有効にし、SSH 経由で CLI にログインします。次に、次のコマンドを実行します。
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. ONTAP tools for VMware vSphereをデプロイします。
. 移行する vCenter Server インスタンスを、 ONTAP tools for VMware vSphereに追加します。参照link:../configure/add-vcenter.html["vCenter Serverインスタンスを追加する"]詳細についてはこちらをご覧ください。
. ONTAPツール プラグインの vCenter Server API からストレージ バックエンドをローカルにオンボードします。
. 移行するには、Swagger または Postman から次の API を発行します。
+
カール -X POST  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs``

+
次の URL から Swagger にアクセスできます。  `\https://$FQDN_IP_PORT/', for example: `\https://10.67.25.33:8443` 。

+
[]
====
*HTTPメソッドとエンドポイント*

このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

|===


| *HTTPメソッド* | *パス* 


| POST | /api/v1 
|===
*処理タイプ*

非同期

*カールの例*

カール -X POST'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs'[] \ --header 'x-auth: <auth_token>' \ --header 'Content-Type: application/json' \ --data '{ "otv_ip": "xx.xx.xx.xx", "vasa_provider_credentials": { "username": "xxxxx", "password": "******" }, "database_password": "******" }'

他のリリース移行のリクエスト本文:

{ "otv_ip": "xx.xx.xx.xx", "vasa_provider_credentials": { "ユーザー名": "xxxxx", "パスワード": "*******" } }

*JSON出力例*

ジョブ オブジェクトが返されます。次のステップで使用するためにジョブ ID を保存する必要があります。

{ "id": 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "実行中" }

====
. ステータスを確認するには、Swagger で次の URI を使用します。
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true`
----
+
ジョブが完了したら、移行レポートを確認します。このレポートはジョブ データに含まれており、ジョブ応答からアクセスできます。

. ONTAP tools for VMware vSphereをvCenter Serverに追加し、link:../configure/registration-process.html["VASAプロバイダーを登録する"] ONTAP tools for VMware vSphereを使用します。
. link:../manage/enable-services.html["VASA Provider の有効化"]ONTAP tools for VMware vSphereのサービス。
. メンテナンス コンソールから、ONTAP tools for VMware vSphereを停止します。
+
VASA プロバイダーを削除しないでください。

+
古いVASAプロバイダが停止すると、vCenter ServerはONTAP tools for VMware vSphereにフェイルオーバーします。すべてのデータストアと仮想マシンはONTAP tools for VMware vSphereからアクセス可能になり、サービスが提供されます。

. ONTAP tools for VMware vSphere 9.xxx から移行された NFS および VMFS データストアは、データストア検出ジョブがトリガーされた後にのみONTAP tools for VMware vSphere 10.4 に表示されます。このジョブが完了するまでに最大 30 分かかる場合があります。VMware vSphere プラグインのユーザー インターフェイス ページのONTAPツールの概要ページにデータストアが表示されていることを確認します。
. Swagger または Postman で次の API を使用してパッチの移行を実行します。
+
[]
====
*HTTPメソッドとエンドポイント*

このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

|===


| *HTTPメソッド* | *パス* 


| PATCH | /api/v1 
|===
*処理タイプ*

非同期

*カールの例*

curl -X パッチ `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65r7-w345-8ufdbb887d43`

*JSON出力例*

ジョブ オブジェクトが返されます。次のステップで使用するためにジョブ ID を保存する必要があります。

{ "id": 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "実行中" }

パッチ操作のリクエスト本体は空です。


NOTE: UUID は、移行後 API への応答として返される移行 UUID です。

パッチ移行 API を実行すると、すべての VM がストレージ ポリシーに準拠します。

====


.次の手順
移行を完了し、 ONTAPツール 10.4 を vCenter Server に登録したら、次の手順を実行します。

* *検出* が完了するまで待ちます。証明書はすべてのホストで自動的に更新されます。
* データストアおよび仮想マシンの操作を開始する前に、十分な時間を確保してください。必要な待機時間は、構成内のホスト、データストア、および仮想マシンの数によって異なります。待機しない場合、断続的な操作障害が発生する可能性があります。


アップグレード後、仮想マシンのコンプライアンス状態が古くなっている場合、次の手順に従ってストレージ ポリシーを再適用します。

. データストアに移動し、*概要* > *VM ストレージ ポリシー* を選択します。
+
*VM ストレージ ポリシー コンプライアンス* のコンプライアンス ステータスが *古い* と表示されます。

. ストレージVMポリシーと対応するVMを選択します
. *適用*を選択
+
*VM ストレージ ポリシー コンプライアンス* のコンプライアンス ステータスが準拠として表示されるようになりました。



.関連情報
* link:../concepts/rbac-learn-about.html["ONTAP tools for VMware vSphereについて学ぶ"]
* link:../upgrade/upgrade-ontap-tools.html["ONTAP tools for VMware vSphereから 10.4 へのアップグレード"]




== ストレージレプリケーションアダプタ(SRA)を更新する手順

.開始する前に
リカバリプランにおいて、保護サイトとは仮想マシンが現在実行されている場所を指し、リカバリサイトとは仮想マシンがリカバリされる場所を指します。SRMインターフェースには、リカバリプランの状態と、保護サイトとリカバリサイトの詳細が表示されます。リカバリプランでは、「*CleanupP*」ボタンと「*Reprotect*」ボタンは無効になっていますが、「TEST」ボタンと「RUN」ボタンは有効なままです。これは、サイトがデータリカバリの準備ができていることを示します。SRAを移行する前に、一方のサイトが保護状態、もう一方のサイトがリカバリ状態であることを確認してください。


NOTE: フェイルオーバーは完了しているが再保護が保留中の場合は、移行を開始しないでください。移行を続行する前に、再保護プロセスが完了していることを確認してください。テスト フェイルオーバーが進行中の場合は、テスト フェイルオーバーをクリーンアップして移行を開始します。

. VMware Site Recovery で VMware vSphere 9.xx 用のONTAPツール SRA アダプタを削除するには、次の手順に従います。
+
.. VMware Live Site Recovery 構成管理ページに移動します
.. *ストレージ レプリケーション アダプタ* セクションに移動します。
.. 省略記号メニューから*構成のリセット*を選択します。
.. 省略記号メニューから*削除*を選択します。


. 保護サイトと回復サイトの両方でこれらの手順を実行します。
+
.. link:../manage/enable-services.html["ONTAP tools for VMware vSphereを有効にする"]
.. ONTAP tools for VMware vSphereを以下の手順でインストールします。link:../protect/configure-on-srm-appliance.html["VMware Live Site RecoveryアプライアンスでSRAを構成する"] 。
.. VMware Live Site Recovery ユーザー インターフェイス ページで、*アレイの検出* および *デバイスの検出* 操作を実行し、デバイスが移行前と同じように表示されていることを確認します。



