---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: ONTAP Tools for VMware vSphereを導入する前に、導入パッケージのスペース要件とホスト システムのいくつかの基本的な要件について理解しておく必要があります。 
---
= ONTAP tools for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools for VMware vSphereを導入する前に、導入パッケージのスペース要件とホスト システムのいくつかの基本的な要件について理解しておく必要があります。

VMware vCenter Server Virtual Appliance (vCSA) では、ONTAP tools for VMware vSphereを使用できます。  ESXi システムを含むサポートされている vSphere クライアントに、 ONTAP tools for VMware vSphereを展開する必要があります。



== システム要件

* *ノードあたりのインストール パッケージのスペース要件*
+
** 15GB - シンプロビジョニングの場合
** 348GB - シックプロビジョニングの場合


* *ホスト システムのサイズ要件* 展開のサイズに応じて推奨されるメモリは以下の表のとおりです。高可用性 (HA) を展開するには、表に指定されているアプライアンス サイズの 3 倍が必要になります。


|===


| *展開の種類* | *ノードあたりのCPU数* | *ノードあたりのメモリ（GB）* | *ノードあたりのシックプロビジョニングされたディスク容量（GB）* 


| 小規模 | 9 | 18 | 350 


| 中 | 13 | 26 | 350 


| 大規模注: 大規模展開は HA 構成専用です。 | 17 | 34 | 350 
|===

NOTE: バックアップを有効にすると、各ONTAPツール クラスターには、VM が展開されるデータストア上にさらに 50 GB のスペースが必要になります。したがって、非 HA では 400 GB、HA では合計 1100 GB のスペースが必要になります。



== 最低限のストレージとアプリケーションの要件

|===
| ストレージ、ホスト、およびアプリケーション | バージョン要件 


| ONTAP | 9.14.1、9.15.1、9.16.0、9.16.1、および 9.16.1P3 FAS、 ASA A シリーズ、 ASA C シリーズ、 AFF A シリーズ、 AFF C シリーズ、およびASA r2。 


| ONTAPツールがサポートするESXiホスト | 7.0.3以降 


| ONTAPツールはvCenter Serverでサポートされています | 7.0U3以降 


| VASA Provider | 3.0 


| OVAアプリケーション | 10.4 


| ONTAPツール仮想マシンを展開するためのESXiホスト | 7.0U3と8.0U3 


| ONTAPツール仮想マシンを展開するためのvCenter Server | 7.0と8.0 
|===

NOTE: ONTAP tools for VMware vSphere以降、仮想マシンのハードウェアがバージョン 10 から 17 に変更されます。

相互運用性マトリックス ツール (IMT) には、サポートされているONTAP、vCenter Server、ESXi ホスト、およびプラグイン アプリケーションのバージョンに関する最新情報が含まれています。

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Interoperability Matrix Tool"^]



== ポート要件

以下の表は、 NetAppが使用するネットワーク ポートとその用途の概要を示しています。ポートには 3 つの種類があります。

* 外部ポート: これらのポートは、Kubernetes クラスターまたはノードの外部からアクセスできます。これらにより、サービスは外部ネットワークまたはユーザーと通信できるようになり、クラスター環境外のシステムとの統合が可能になります。
* ノード間ポート: これらのポートは、Kubernetes クラスター内のノード間の通信を可能にします。データの共有や共同作業などのクラスター タスクに必要です。単一ノード展開の場合、ノード間ポートはノード内でのみ使用され、外部アクセスは必要ありません。ノード間ポートはクラスター外部からのトラフィックを受け入れることができます。ファイアウォール ルールを使用して、ノード間ポートからのインターネット アクセスをブロックします。
* 内部ポート: これらのポートは、ClusterIP アドレスを使用して Kubernetes クラスター内で通信します。これらは外部に公開されず、ファイアウォール ルールに追加する必要もありません。



NOTE: 中断のない相互通信を維持するために、すべてのONTAPツール ノードが同じサブネット上に存在することを確認します。


|===
| *サービス/コンポーネント名* | *ポート* | *プロトコル* | *ポートタイプ* | *説明* 


| ntv-gateway-svc (LB) | 443, 8443 | TCP | 外部 | VASA プロバイダー サービスの着信通信用のパススルー ポート。VASA プロバイダーの自己署名証明書とカスタム CA 証明書はこのポートでホストされます。 


| SSH | 22 | TCP | 外部 | リモート サーバー ログインおよびコマンド実行用のセキュア シェル。 


| rke2 サーバー | 9345 | TCP | ノード間 | RKE2 スーパーバイザー API (信頼できるネットワークに制限)。 


| kube-apiサーバー | 6443 | TCP | ノード間 | Kubernetes API サーバー ポート (信頼できるネットワークに制限)。 


| rpcbind/ポートマッパー | 111 | TCP/UDP | ノード間 | サービス間の RPC 通信に使用されます。 


| coredns (DNS) | 53 | TCP/UDP | ノード間 | クラスター内の名前解決のためのドメイン ネーム システム (DNS) サービス。 


| NTP | 123 | UDP | ノード間 | 時間同期のためのネットワーク タイム プロトコル (NTP)。 


| など | 2379、2380、2381 | TCP | ノード間 | クラスター データのキー値ストア。 


| kube-vip | 2112 | TCP | ノード間 | Kubernetes API サーバー ポート。 


| クベレット | 10248, 10250 | TCP | ノード間 | Kubernetesコンポーネント 


| kubeコントローラー | 10257 | TCP | ノード間 | Kubernetesコンポーネント 


| クラウドコントローラー | 10258 | TCP | ノード間 | Kubernetesコンポーネント 


| kubeスケジューラ | 10259 | TCP | ノード間 | Kubernetesコンポーネント 


| kubeプロキシ | 10249, 10256 | TCP | ノード間 | Kubernetesコンポーネント 


| カリコノード | 9091、9099 | TCP | ノード間 | Calico ネットワーク コンポーネント。 


| コンテナ | 10010 | TCP | ノード間 | コンテナ デーモン サービス。 


| VXLAN（フランネル） | 8472 | UDP | ノード間 | ポッド通信用のオーバーレイ ネットワーク。 
|===

NOTE: HA 展開の場合、すべてのノード間で UDP ポート 8472 が開いていることを確認します。このポートはノード間のポッド間通信を可能にします。これをブロックすると、ノード間ネットワークが中断されます。



== ONTAP tools for VMware vSphereを導入するための構成制限

次の表をガイドとして使用して、 ONTAP tools for VMware vSphereを構成することができます。

|===


| *展開* | *タイプ* | * vVolsの数* | *ホスト数* 


| HA 認定外 | 小（S） | 約12K | 32 


| HA 認定外 | ミディアム（M） | 約24K | 64 


| 高可用性 | 小（S） | 約24K | 64 


| 高可用性 | ミディアム（M） | 約5万 | 128 


| 高可用性 | ラージ（L） | 約10万 | 256 [注意] 表内のホストの数は、複数の vCenter からのホストの合計数を示しています。 
|===


== ONTAP tools for VMware vSphere- ストレージ レプリケーション アダプタ (SRA)

次の表は、ONTAP tools for VMware vSphereを使用して VMware Live Site Recovery インスタンスごとにサポートされる数を示しています。

|===
| *vCenter 展開サイズ* | *小さい* | *中くらい* 


| アレイベースのレプリケーションを使用して保護するように構成された仮想マシンの合計数 | 2000 | 5000 


| アレイベースのレプリケーション保護グループの合計数 | 250 | 250 


| 復旧計画ごとの保護グループの合計数 | 50 | 50 


| 複製されたデータストアの数 | 255 | 255 


| VM 数 | 4000 | 7000 
|===
次の表は、ONTAP tools for VMware vSphereを示しています。

|===


| *VMware Live Site Recoveryインスタンスの数* | * ONTAPツールの導入サイズ* 


| 最大4 | 小規模 


| 4～8 | 中 


| 8以上 | 大規模 
|===
 https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["VMware Live Site Recovery の運用上の制限"] 。
