---
permalink: protect/configure-storage-replication-adapter-for-highly-scaled-environment.html 
sidebar: sidebar 
keywords:  
summary: '大規模環境でストレージ レプリケーション アダプタ (SRA) が最適に機能するには、推奨設定に従ってストレージ タイムアウト間隔を構成する必要があります。' 
---
= 大規模環境向けに SRA を構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
大規模環境でストレージ レプリケーション アダプタ (SRA) が最適に機能するには、推奨設定に従ってストレージ タイムアウト間隔を構成する必要があります。



== ストレージ プロバイダの設定

拡張環境の場合、VMware Live Site Recovery で次のタイムアウト値を設定する必要があります。

|===


| *詳細設定* | *タイムアウト値* 


 a| 
`StorageProvider.resignatureTimeout`
 a| 
値を900秒から12000秒に引き上げます。



 a| 
`storageProvider.hostRescanDelaySec`
 a| 
60



 a| 
`storageProvider.hostRescanRepeatCnt`
 a| 
20



 a| 
`storageProvider.hostRescanTimeoutSec`
 a| 
高い値を設定します（例：99999）

|===
また、 `StorageProvider.autoResignatureMode`オプション。

参照 https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/how-do-i-protect-my-environment/advanced-srm-configuration/reconfigure-srm-settings/change-storage-provider-settings.html["Change Storage Provider Settings"]ストレージ プロバイダー設定の変更の詳細については、こちらをご覧ください。



== ストレージ設定

タイムアウトになったら、 `storage.commandTimeout`そして `storage.maxConcurrentCommandCnt`より高い価値へ。


NOTE: このタイムアウト間隔は最大値です。最大タイムアウトに達することはありません。ほとんどのコマンドは、設定された最大タイムアウト間隔以内に終了します。

参照 https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/how-do-i-protect-my-environment/advanced-srm-configuration/reconfigure-srm-settings/change-storage-settings.html["Change Storage Settings"]SAN プロバイダーの設定を変更するため。
