---
permalink: protect/configure-array-manager.html 
sidebar: sidebar 
keywords:  
summary: 'VMware Live Site Recovery のアレイ マネージャ ウィザードを使用してストレージ レプリケーション アダプタ (SRA) を構成し、VMware Live Site Recovery とストレージ仮想マシン (SVM) 間のやり取りを有効にすることができます。' 
---
= アレイ マネージャを使用したSRAの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware Live Site Recovery のアレイ マネージャ ウィザードを使用してストレージ レプリケーション アダプタ (SRA) を構成し、VMware Live Site Recovery とストレージ仮想マシン (SVM) 間の対話を有効にすることができます。

.開始する前に
* VMware Live Site Recovery で保護サイトとリカバリ サイトをペアリングしておく必要があります。
* アレイ マネージャーを構成する前に、オンボード ストレージを構成しておく必要があります。
* 保護されたサイトとリカバリ サイト間のSnapMirror関係を構成して複製しておく必要があります。
* マルチテナントを有効にするには、SVM 管理 LIF を有効にする必要があります。


SRAでは、クラスタレベルの管理とSVMレベルの管理がサポートされます。クラスター レベルでストレージを追加すると、クラスター内のすべての SVM を検出して操作を実行できます。SVMレベルでストレージを追加する場合は、特定のSVMだけを管理できます。

.手順
. VMware Live Site Recovery で、*アレイ マネージャ* > *アレイ マネージャの追加* を選択します。
. VMware Live Site Recovery でアレイを説明するには、次の情報を入力します。
+
.. *表示名* フィールドにアレイ マネージャーを識別するための名前を入力します。
.. *SRA タイプ* フィールドで、* NetApp Storage Replication Adapter for ONTAP* を選択します。
.. クラスタまたはSVMへの接続情報を入力します。
+
*** クラスタに接続する場合は、クラスタ管理LIFを入力する必要があります。
*** SVM に直接接続する場合は、SVM 管理 LIF の IP アドレスを入力する必要があります。
+

NOTE: アレイ マネージャを構成するときは、 ONTAP tools for VMware vSphereでストレージ システムをオンボードするために使用したのと同じ接続 (IP アドレス) をストレージ システムに使用する必要があります。たとえば、アレイ マネージャ構成が SVM 範囲である場合、 ONTAP tools for VMware vSphereの下のストレージを SVM レベルで追加する必要があります。



.. クラスターに接続する場合は、*SVM 名* フィールドに SVM 名を指定するか、クラスター内のすべての SVM を管理するには空白のままにします。
.. *ボリューム包含リスト* フィールドに検出するボリュームを入力します。
+
保護対象サイト側のソース ボリューム、およびリカバリ サイト側のレプリケートされたデスティネーション ボリュームを入力できます。

+
たとえば、ボリューム dst_vol1 とSnapMirror関係にあるボリューム src_vol1 を検出する場合は、保護サイト フィールドに src_vol1 を指定し、リカバリ サイト フィールドに dst_vol1 を指定する必要があります。

.. *(オプション)*「ボリューム除外リスト」フィールドに、検出から除外するボリュームを入力します。
+
保護対象サイト側のソース ボリューム、およびリカバリ サイト側のレプリケートされたデスティネーション ボリュームを入力できます。

+
たとえば、ボリューム _dst_vol1_ とSnapMirror関係にあるボリューム _src_vol1_ を除外する場合は、保護サイト フィールドに _src_vol1_ を指定し、リカバリ サイト フィールドに _dst_vol1_ を指定する必要があります。



. *次へ*を選択します。
. アレイが検出され、「アレイ マネージャーの追加」ウィンドウの下部に表示されていることを確認し、「完了」を選択します。


該当するSVMの管理IPアドレスとクレデンシャルを使用して、リカバリ サイトでも同じ手順を実行します。Add Array Managerウィザードの[Enable Array Pairs]画面で、正しいアレイ ペアが選択されていて、有効化できる状態になっていることを確認します。
