---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: 保護されたサイト上の仮想マシンのグループを保護するには、保護グループを作成する必要があります。 
---
= 保護対象サイトとリカバリ サイトの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
保護されたサイト上の仮想マシンのグループを保護するには、保護グループを作成する必要があります。

新しいデータストアを追加する際は、既存のデータストアグループに含めるか、新しいデータストアを追加して保護用の新しいボリュームまたはコンシステンシグループを作成することができます。保護対象のコンシステンシグループまたはボリュームに新しいデータストアを追加したら、 SnapMirrorを更新し、保護対象サイトとリカバリサイトの両方でストレージ検出を実行します。新しいデータストアを確実に検出・保護するために、検出を手動で実行することも、スケジュールに従って実行することもできます。



== 保護対象サイトとリカバリ サイトのペアリング

ストレージ レプリケーション アダプタ (SRA) がストレージ システムを検出できるようにするには、vSphere Client を使用して作成された保護サイトとリカバリ サイトをペアリングする必要があります。


NOTE: ストレージ レプリケーション アダプタ (SRA) は、整合性グループ上の自動フェイルオーバー デュプレックス タイプの 1 つの同期関係と非同期関係SnapMirrorによるファンアウトをサポートします。ただし、整合性グループ上の 2 つの非同期SnapMirrorを使用したファンアウト、またはボリューム上のファンアウト SnapMirror はサポートされていません。

.開始する前に
* 保護サイトとリカバリ サイトに VMware Live Site Recovery がインストールされている必要があります。
* 保護サイトとリカバリ サイトに SRA をインストールする必要があります。


.手順
. vSphere Client ホームページで *Site Recovery* をダブルクリックし、*Sites* を選択します。
. *オブジェクト* > *アクション* > *サイトのペア*を選択します。
. *Site Recovery Manager サーバーのペアリング* ダイアログ ボックスで、保護されたサイトの Platform Services Controller のアドレスを入力し、*次へ* を選択します。
. [Select vCenter Server]セクションで、次の手順を実行します。
+
.. 保護対象サイトのvCenter Serverが対応するペア候補として表示されていることを確認します。
.. SSO 管理者の資格情報を入力し、[完了] を選択します。


. プロンプトが表示されたら、「*はい*」を選択してセキュリティ証明書を受け入れます。


.結果
保護されたサイトと回復サイトの両方が [オブジェクト] ダイアログ ボックスに表示されます。



== 保護グループの設定

.開始する前に
ソース サイトとターゲット サイトの両方で以下が設定されていることを確認する必要があります。

* 同じバージョンの VMware Live Site Recovery がインストールされている
* 仮想マシン
* 保護対象サイトとリカバリ サイトがペアリングされている
* ソースとデスティネーションのデータストアがそれぞれのサイトにマウントされている


.手順
. vCenter Server にログインし、*Site Recovery* > *Protection Groups* を選択します。
. *保護グループ* ペインで、*新規* を選択します。
. 保護グループの名前と説明、方向を指定して、[次へ] を選択します。
. *タイプ*フィールドで、*タイプフィールドオプション...*として、NFSおよびVMFSデータストアのデータストアグループ（アレイベースレプリケーション）を選択します。フォールト ドメインは、実際には、レプリケーションが有効になっているSVMです。ピアリングのみが実装されており、問題のないSVMが表示されます。
. [レプリケーション グループ] タブで、有効なアレイ ペアまたは構成した仮想マシンが含まれるレプリケーション グループのいずれかを選択し、[次へ] を選択します。
+
レプリケーション グループ上のすべての仮想マシンが保護グループに追加されます。

. 既存のリカバリ プランを選択するか、[新しいリカバリ プランに追加] を選択して新しいリカバリ プランを作成することもできます。
. [準備完了] タブで、作成した保護グループの詳細を確認し、[完了] を選択します。

