---
permalink: concepts/ontap-tools-concepts-terms.html 
sidebar: sidebar 
keywords:  
summary: 次のセクションでは、このドキュメントで使用されている主要な概念と用語について説明します。 
---
= 重要な概念と用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次のセクションでは、このドキュメントで使用されている主要な概念と用語について説明します。



=== ASA r2 システム

新しいNetApp ASA r2 システムは、SAN のみを利用するお客様のニーズに合わせた簡素化されたエクスペリエンスを実現する、統合されたハードウェアおよびソフトウェア ソリューションを提供します。 https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 ストレージシステムについて学ぶ"] 。



=== 認証局（CA）

CA は、Secure Sockets Layer (SSL) 証明書を発行する信頼できるエンティティです。



=== 一貫性グループ（CG）

整合性グループは、単一のユニットとして管理されるボリュームの集合です。CG は、ストレージ ユニットおよびボリューム間でデータの一貫性を保つために同期されます。ONTAPでは、複数のボリュームにまたがるアプリケーション ワークロードの管理が容易になり、保護が保証されます。詳細はこちら https://docs.netapp.com/us-en/ontap/consistency-groups/index.html["一貫性グループ"]。



=== デュアルスタック

デュアルスタック ネットワークは、IPv4 アドレスと IPv6 アドレスの同時使用をサポートするネットワーク環境です。



=== 高可用性（HA）

クラスタ ノードは、中断のない操作のために HA ペアで構成されます。



=== 論理ユニット番号（LUN）

LUN は、ストレージ エリア ネットワーク (SAN) 内の論理ユニットを識別するために使用される番号です。これらのアドレス指定可能なデバイスは、通常はSCSI（Small Computer System Interface）プロトコルやそのカプセル化された派生プロトコルの1つを介してアクセスされる論理ディスクです。



=== NVMe名前空間とサブシステム

NVMeネームスペースは、論理ブロックにフォーマット可能な不揮発性メモリの容量です。ネームスペースはFCおよびiSCSIプロトコルのLUNに相当し、NVMeサブシステムはigroupに相当します。NVMe サブシステムをイニシエーターに関連付けることで、関連付けられたイニシエーターがサブシステム内の名前空間にアクセスできるようになります。



=== ONTAPツールマネージャー

ONTAPツール マネージャーは、管理対象 vCenter Server インスタンスおよびオンボード ストレージ バックエンドに対するONTAP tools for VMware vSphereをより細かく制御できるようにします。  vCenter Server インスタンス、ストレージ バックエンド、証明書、パスワード、およびログ バンドルのダウンロードの管理に役立ちます。



=== オープン仮想アプライアンス (OVA)

OVA は、仮想マシン上で実行する必要がある仮想アプライアンスまたはソフトウェアをパッケージ化して配布するためのオープン スタンダードです。



=== 復旧ポイント目標（RPO）

RPO は、データをバックアップまたは複製する頻度を測定します。業務を再開するために、障害後にデータを復元する必要がある正確な時点を指定します。たとえば、組織の RPO が 4 時間の場合、災害発生時に最大 4 時間分のデータの損失を許容できます。



=== SnapMirrorアクティブ同期

SnapMirrorアクティブ シンクにより、サイト全体の障害が発生した場合でもビジネス サービスは継続して稼働でき、セカンダリ コピーを使用してアプリケーションを透過的にフェイルオーバーできます。 SnapMirror Active Sync でフェイルオーバーをトリガーするには、手動による介入やカスタム スクリプトは必要ありません。詳細はこちら https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["SnapMirrorアクティブ同期"]。



=== ストレージバックエンド

ストレージ バックエンドは、ESXi ホストが仮想マシンのファイル、データ、およびその他のリソースを保存するために使用する基盤となるストレージ インフラストラクチャです。これらにより、ESXi ホストは永続データにアクセスして管理できるようになり、仮想化環境に必要なストレージ機能とパフォーマンスが提供されます。

.グローバル クラスター (ストレージ バックエンド)
ONTAPクラスタ認証情報でのみ使用可能なグローバル ストレージ バックエンドは、 ONTAPツール マネージャ インターフェイスを通じてオンボードされます。最小限の権限で追加することで、 vVols管理に必要な重要なクラスター リソースの検出が可能になります。グローバル クラスターは、 vVols管理のために SVM ユーザーがローカルに追加されるマルチテナント シナリオに最適です。

.ローカルストレージバックエンド
クラスタまたは SVM 認証情報を持つローカル ストレージ バックエンドは、 ONTAPツールのユーザー インターフェイスを通じて追加され、vCenter に制限されます。クラスタ認証情報をローカルで使用する場合、関連付けられた SVM は vCenter と自動的にマッピングされ、 vVolsまたは VMFS を管理します。  SRA を含む VMFS 管理の場合、 ONTAPツールはグローバル クラスタを必要とせずに SVM 認証情報をサポートします。



=== Storage Replication Adapter（SRA）

SRA は、VMware Live Site Recovery アプライアンス内にインストールされるストレージ ベンダー固有のソフトウェアです。このアダプタにより、Storage Virtual Machine (SVM) レベルおよびクラスタ レベルの構成で、Site Recovery Manager とストレージ コントローラ間の通信が可能になります。



=== ストレージ仮想マシン (SVM)

SVM は、 ONTAPにおけるマルチテナンシーの単位です。ハイパーバイザー上で実行される仮想マシンと同様に、SVM は物理リソースを抽象化する論理エンティティです。  SVM には、データ ボリュームと、クライアントにデータを提供する 1 つ以上の LIF が含まれています。



=== 均一な構成と非均一な構成

* *均一なホスト アクセス* とは、2 つのサイトのホストが両方のサイトのストレージ クラスターへのすべてのパスに接続されていることを意味します。サイト間のパスは長距離にわたって伸びます。
* *非均一ホスト アクセス* とは、各サイト内のホストが同じサイト内のクラスターにのみ接続されていることを意味します。サイト間パスと拡張パスは接続されません。
+

NOTE: 均一なホスト アクセスは、すべてのSnapMirrorアクティブ同期構成でサポートされます。不均一なホスト アクセスは、対称アクティブ / アクティブ構成でのみサポートされます。詳細はこちら https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["ONTAPにおけるSnapMirrorアクティブ同期の概要"]。





=== Virtual Machine File System（VMFS）

VMFS は、VMware vSphere 環境で仮想マシン ファイルを保存するために設計されたクラスター化されたファイル システムです。



=== 仮想ボリューム（vVols）

vVols は、仮想マシンで使用されるストレージのボリューム レベルの抽象化を提供します。これにはいくつかの利点があり、従来のLUNの代わりに使用できます。vVol データストアは通常、 vVolsのコンテナとして機能する単一の LUN に関連付けられます。



=== VM ストレージ ポリシー

VM ストレージ ポリシーは、vCenter Server のポリシーとプロファイルの下に作成されます。  vVolsの場合、 NetApp vVolsストレージ タイプ プロバイダーのルールを使用してルール セットを作成します。



=== VMware ライブサイトリカバリ

VMware Live Site Recovery (旧称 Site Recovery Manager (SRM)) は、VMware 仮想環境のビジネス継続性、災害復旧、サイト移行、および中断のないテスト機能を提供します。



=== VMware vSphere APIs for Storage Awareness (VASA)

VASA は、管理および運営のためにストレージ アレイを vCenter Server と統合する API セットです。アーキテクチャは、VMware vSphere とストレージ システム間の通信を処理する VASA プロバイダーを含む複数のコンポーネントに基づいています。



=== VMware vSphere ストレージ API - アレイ統合 (VAAI)

VAAI は、VMware vSphere ESXi ホストとストレージ デバイス間の通信を可能にする API セットです。 API には、ホストがストレージ操作をアレイにオフロードするために使用する一連の基本操作が含まれています。VAAIは、ストレージを大量に消費するタスクのパフォーマンスを大幅に向上させることができます。



=== vSphere Metro Storage Cluster

vSphere Metro Storage Cluster (vMSC) は、ストレッチ クラスタ展開で vSphere を有効にしてサポートするアーキテクチャです。vMSC ソリューションは、 NetApp MetroClusterおよびSnapMirror Active Sync (旧称 SMBC) でサポートされています。これらのソリューションは、ドメインに障害が発生した場合のビジネス継続性を強化します。耐障害性モデルは、お客様が選択した構成に基づいています。詳細はこちら https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-vmsc["VMware vSphere Metro ストレージ クラスタ"]。



=== vVolsデータストア

vVolsデータストアは、VASA プロバイダーによって作成および管理されるvVolsコンテナの論理データストア表現です。



=== RPOゼロ

RPO は目標復旧ポイントの略で、特定の時間内に許容できるとみなされるデータ損失の量です。RPOゼロとは、データ損失が一切許容されないことを意味します。
