---
permalink: concepts/rbac-learn-about.html 
sidebar: sidebar 
keywords: role based access control, rbac, rbac components, learn about rbac 
summary: 'ロールベース アクセス制御 (RBAC) は、組織内のリソースへのアクセスを制御するためのセキュリティ フレームワークです。 RBAC は、個々のユーザーに承認を割り当てるのではなく、アクションを実行するための特定のレベルの権限を持つロールを定義することで管理を簡素化します。定義されたロールがユーザーに割り当てられるため、エラーのリスクが軽減され、組織全体のアクセス制御の管理が簡素化されます。' 
---
= ONTAP tools for VMware vSphereについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ロールベース アクセス制御 (RBAC) は、組織内のリソースへのアクセスを制御するためのセキュリティ フレームワークです。 RBAC は、個々のユーザーに承認を割り当てるのではなく、アクションを実行するための特定のレベルの権限を持つロールを定義することで管理を簡素化します。定義されたロールがユーザーに割り当てられるため、エラーのリスクが軽減され、組織全体のアクセス制御の管理が簡素化されます。

RBAC 標準モデルは、複雑さが増す複数の実装テクノロジまたはフェーズで構成されています。その結果、実際の RBAC の展開は、ソフトウェア ベンダーとその顧客のニーズに基づいて、比較的単純なものから非常に複雑なものまで多岐にわたる可能性があります。



== RBAC コンポーネント

大まかに言うと、すべての RBAC 実装に一般的に含まれるコンポーネントがいくつかあります。これらのコンポーネントは、承認プロセスの定義の一環として、さまざまな方法で結合されます。

.権限
_権限_とは、許可または拒否できるアクションまたは機能です。ファイルの読み取り権限のような単純なものから、特定のソフトウェアシステムに固有のより抽象的な操作まで、多岐にわたります。また、REST APIエンドポイントやCLIコマンドへのアクセスを制限するためにPrivilegesを定義することもできます。すべてのRBAC実装には、事前定義された権限が含まれており、管理者がカスタム権限を作成できる場合もあります。

.役割
_ロール_ は、1 つ以上の権限を含むコンテナーです。役割は通常、特定のタスクまたは職務機能に基づいて定義されます。ユーザーにロールが割り当てられると、そのロールに含まれるすべての権限がユーザーに付与されます。また、権限と同様に、実装には事前定義されたロールが含まれており、通常はカスタム ロールの作成も許可されます。

.オブジェクト
_オブジェクト_ は、RBAC 環境内で識別される実際のリソースまたは抽象リソースを表します。権限を通じて定義されたアクションは、関連付けられたオブジェクトに対して、または関連付けられたオブジェクトを使用して実行されます。実装に応じて、オブジェクト タイプまたは特定のオブジェクト インスタンスに権限を付与できます。

.ユーザとグループ
_ユーザー_ は、認証後に適用されるロールに割り当てられるか、関連付けられます。一部の RBAC 実装では、ユーザーに割り当てられるロールは 1 つだけですが、他の実装では、ユーザーごとに複数のロールが許可され、一度にアクティブにできるロールは 1 つだけになる場合があります。グループにロールを割り当てると、セキュリティ管理がさらに簡素化されます。

.権限
_権限_ は、ユーザーまたはグループをロールとともにオブジェクトにバインドする定義です。権限は、階層オブジェクト モデルで役立ち、階層内の子にオプションで継承できます。



== 2つのRBAC環境

ONTAP tools for VMware vSphereを使用する場合は、考慮する必要がある 2 つの異なる RBAC 環境があります。

.VMware vCenter Server
VMware vCenter Server の RBAC 実装は、vSphere Client ユーザー インターフェイスを通じて公開されるオブジェクトへのアクセスを制限するために使用されます。 ONTAP tools for VMware vSphereのインストールの一環として、RBAC 環境が拡張され、 ONTAPツールの機能を表す追加オブジェクトが含まれるようになります。これらのオブジェクトへのアクセスはリモートプラグインを通じて提供されます。link:../concepts/rbac-vcenter-environment.html["vCenter Server RBAC 環境"]詳細についてはこちらをご覧ください。

.ONTAPクラスタ
ONTAP tools for VMware vSphereは、 ONTAP REST API を介してONTAPクラスターに接続し、ストレージ関連の操作を実行します。ストレージ リソースへのアクセスは、認証時に提供されたONTAPユーザーに関連付けられたONTAPロールを通じて制御されます。見るlink:../concepts/rbac-ontap-environment.html["ONTAP RBAC環境"]詳細についてはこちらをご覧ください。
