---
permalink: concepts/rbac-ontap-use.html 
sidebar: sidebar 
keywords: ontap rbac, use ontap rbac 
summary: ONTAPを使用したONTAP tools for VMware vSphereには、実稼働環境で使用する前に考慮すべきいくつかの側面があります。 
---
= ONTAP tools for VMware vSphereでONTAP RBAC を使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPを使用したONTAP tools for VMware vSphereには、実稼働環境で使用する前に考慮すべきいくつかの側面があります。



== 構成プロセスの概要

ONTAP tools for VMware vSphereには、カスタム ロールを持つONTAPユーザーの作成のサポートが含まれています。定義は、 ONTAPクラスターにアップロードできる JSON ファイルにパッケージ化されています。ユーザーを作成し、環境とセキュリティのニーズに合わせてロールをカスタマイズできます。

主要な構成手順の概要を以下に説明します。参照link:../configure/configure-user-role-and-privileges.html["ONTAPユーザーの役割と権限を構成する"]詳細についてはこちらをご覧ください。

.1.準備
ONTAPツール マネージャーとONTAPクラスターの両方の管理者資格情報が必要です。

.2.JSON定義ファイルをダウンロードする
ONTAP Tools Manager ユーザー インターフェイスにサインインした後、RBAC 定義を含む JSON ファイルをダウンロードできます。

.3.ロールを持つONTAPユーザーを作成する
System Manager にサインインしたら、ユーザーとロールを作成できます。

. 左側の*クラスター*を選択し、次に*設定*を選択します。
. *ユーザーとロール*までスクロールしてクリックします `-->`。
. *ユーザー*の下の*追加*を選択し、*仮想化製品*を選択します。
. ローカルワークステーション上の JSON ファイルを選択し、アップロードします。


.4.役割を構成する
役割を定義する一環として、いくつかの管理上の決定を行う必要があります。見る<<システムマネージャを使用してロールを構成する>>詳細についてはこちらをご覧ください。



== システムマネージャを使用してロールを構成する

System Manager を使用して新しいユーザーとロールの作成を開始し、JSON ファイルをアップロードしたら、環境とニーズに応じてロールをカスタマイズできます。



=== コアユーザーとロールの構成

RBAC 定義は、VSC、VASA プロバイダー、SRA の組み合わせを含む複数の製品機能としてパッケージ化されています。 RBAC サポートが必要な環境を選択する必要があります。たとえば、ロールでリモート プラグイン機能をサポートする場合は、VSC を選択します。ユーザー名と関連するパスワードも選択する必要があります。



=== 権限

ロール権限は、 ONTAPストレージに必要なアクセス レベルに基づいて 4 つのセットに分類されます。ロールのベースとなる権限は次のとおりです。

* Discovery
+
ストレージ システムを追加できます。

* ストレージの作成
+
ストレージを作成できます。また、検出ロールに関連付けられているすべての権限も含まれます。

* ストレージを変更する
+
ストレージを変更できます。また、ストレージの検出および作成のロールに関連付けられているすべての権限も含まれます。

* ストレージを破壊する
+
ストレージを破棄できます。また、検出、ストレージの作成、ストレージ ロールの変更に関連するすべての権限も含まれます。





=== ロールを持つユーザーを生成する

環境の設定オプションを選択したら、[*追加*] をクリックすると、 ONTAPによってユーザーとロールが作成されます。生成されたロールの名前は、次の値の連結になります。

* JSON ファイルで定義された定数プレフィックス値 (例: "OTV_10")
* 選択した製品の機能
* 権限セットのリスト。


.例
`OTV_10_VSC_Discovery_Create`

新しいユーザーは、「ユーザーとロール」ページのリストに追加されます。  HTTP と ONTAPI の両方のユーザー ログイン方法がサポートされていることに注意してください。
