---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: ストレージ バックエンドは、ESXi ホストがデータ ストレージに使用するシステムです。 
---
= ストレージバックエンドを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ バックエンドを追加すると、 ONTAPクラスターをオンボードできるようになります。

*このタスクについて*

vCenter が関連付けられた SVM を持つテナントとして機能するマルチテナント設定の場合は、 ONTAPツール マネージャを使用してクラスタを追加します。ストレージ バックエンドを vCenter Server に関連付けて、オンボードされた vCenter Server インスタンスにグローバルにマップします。 vCenter テナントは、必要なストレージ仮想マシン (SVM) をオンボードする必要があります。これにより、SVM ユーザーはvVolsデータストアをプロビジョニングできるようになります。  SVM を使用して vCenter にストレージを追加できます。

ONTAPツールのユーザー インターフェイスを使用して、クラスタまたは SVM 認証情報を持つローカル ストレージ バックエンドを追加します。これらのストレージ バックエンドは、単一の vCenter に制限されます。クラスタ認証情報をローカルで使用する場合、関連付けられた SVM は自動的に vCenter にマッピングされ、 vVolsまたは VMFS を管理します。  SRA を含む VMFS 管理の場合、 ONTAPツールはグローバル クラスタを必要とせずに SVM 認証情報をサポートします。

[role="tabbed-block"]
====
.ONTAPツールマネージャの使用
--

NOTE: マルチテナント設定では、ストレージ バックエンド クラスターをグローバルに追加し、SVM をローカルに追加して、SVM ユーザー資格情報を使用できます。

.手順
. Web ブラウザからONTAPツール マネージャを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者認証情報を使用してログインします。
. サイドバーから*ストレージ バックエンド*を選択します。
. ストレージ バックエンドを追加し、サーバーの IP アドレスまたは FQDN、ユーザー名、およびパスワードの詳細を指定します。
+

NOTE: IPv4 および IPv6 アドレス管理 LIF がサポートされています。



--
.vSphere クライアント ユーザー インターフェイスの使用
--

NOTE: vSphere クライアント ユーザー インターフェイスを通じてストレージ バックエンドを構成する場合、 vVolsデータストアでは SVM ユーザーの直接追加がサポートされていないことに注意することが重要です。

. vSphere クライアントにログインします。
. ショートカット ページで、プラグイン セクションの * NetApp ONTAPツール* を選択します。
. サイドバーから*ストレージ バックエンド*を選択します。
. ストレージ バックエンドを追加し、サーバーの IP アドレス、ユーザー名、パスワード、ポートの詳細を指定します。
+

NOTE: SVM ユーザーを直接追加するには、クラスタベースの認証情報と IPv4 および IPv6 アドレス管理 LIF を追加するか、SVM 管理 LIF を使用して SVM ベースの認証情報を提供します。



.次は何？
リストが更新され、新しく追加されたストレージ バックエンドがリストに表示されます。

--
====