---
permalink: configure/protect-cluster.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: ONTAP tools for VMware vSphereは、ホスト クラスターの保護を管理します。 
---
= ホストクラスタ保護を使用して保護する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereは、ホスト クラスターの保護を管理します。選択した SVM に属し、クラスタの 1 つ以上のホストにマウントされているすべてのデータストアは、ホスト クラスタの下で保護されます。

.開始する前に
次の前提条件が満たされていることを確認してください。

* ホスト クラスタには、1 つの SVM のデータストアのみが含まれます。
* ホスト クラスターにマウントされたデータストアは、クラスター外部のホストにマウントしないでください。
* ホスト クラスターにマウントされるすべてのデータストアは、iSCSI/FC プロトコルを使用した VMFS データストアである必要があります。NVMe/FC および NVMe/TCP プロトコルを使用したvVols、NFS、または VMFS データストアはサポートされていません。
* ホスト クラスタにマウントされたデータストアを形成するFlexVol/LUN は、既存の整合性グループ (CG) の一部であってはなりません。
* ホスト クラスタにマウントされたFlexVol/LUN 形成データストアは、既存のSnapMirror関係の一部であってはなりません。
* ホスト クラスターには少なくとも 1 つのデータストアが必要です。


.手順
. vSphere クライアントにログインします。
. ホスト クラスターを右クリックし、* NetApp ONTAPツール* > *クラスターの保護* を選択します。
. 保護クラスタ ウィンドウでは、データストア タイプとソース ストレージ仮想マシン (VM) の詳細が自動的に入力されます。保護されたデータストアを表示するには、データストア リンクを選択します。
. *整合性グループ名*を入力します。
. *関係を追加*を選択します。
. * SnapMirror関係の追加* ウィンドウで、*ターゲット ストレージ VM* と *ポリシー* タイプを選択します。
+
ポリシー タイプは、非同期または自動フェールオーバーデュプレックスにすることができます。

+
SnapMirror関係を AutomatedFailOverDuplex タイプのポリシーとして追加する場合は、 ONTAP tools for VMware vSphereが展開されているのと同じ vCenter に、ターゲット ストレージ VM をストレージ バックエンドとして追加する必要があります。

+
AutomatedFailOverDuplex ポリシー タイプには、均一なホスト構成と非均一なホスト構成があります。*均一ホスト構成*トグル ボタンを選択すると、ホスト イニシエーター グループ構成がターゲット サイトに暗黙的に複製されます。詳細については、link:../concepts/ontap-tools-concepts-terms.html["重要な概念と用語"] 。

. 非均一なホスト構成を選択する場合は、そのクラスター内の各ホストのホスト アクセス (ソース/ターゲット) を選択します。
. *追加*を選択します。
. *クラスターの保護*ウィンドウでは、作成操作中に保護されたクラスターを編集することはできません。削除して再度保護を追加することができます。ホスト クラスター保護の変更操作中に、編集オプションが利用できます。省略記号メニュー オプションを使用して、関係を編集または削除できます。
. *保護*ボタンを選択します。
+
ジョブ ID の詳細を含む vCenter タスクが作成され、その進行状況が最近のタスク パネルに表示されます。これは非同期タスクです。ユーザー インターフェイスにはリクエストの送信ステータスのみが表示され、タスクが完了するまで待機しません。

. 保護されたホスト クラスターを表示するには、* NetApp ONTAPツール* > *保護* > *ホスト クラスター リレーションシップ* に移動します。

