---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphereの 1 つのインスタンスで、複数の vCenter Server インスタンスを管理できます。 ONTAP tools for VMware vSphereは、 VASA プロバイダーの自己署名証明書を使用して導入されます。これにより、 vVolsデータストアに対して 1 つの vCenter Server インスタンスのみを管理できるようになります。 
---
= 証明書の管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
導入時に、 ONTAPツールおよび VASA プロバイダー用の自己署名証明書がデフォルトで生成されます。 ONTAPツール マネージャ インターフェイスを使用して、証明書を更新したり、カスタム CA にアップグレードしたりできます。マルチ vCenter 展開ではカスタム CA 証明書が必須です。

.開始する前に
* 証明書が発行されるドメイン名は、仮想 IP アドレスにマッピングする必要があります。
* ドメイン名に対して nslookup チェックを実行し、ドメインが意図した IP アドレスに解決されているかどうかを確認します。
* 証明書は、ドメイン名とONTAPツールの IP アドレスを使用して作成する必要があります。



NOTE: ONTAPツールの IP アドレスは、完全修飾ドメイン名 (FQDN) にマッピングする必要があります。証明書には、サブジェクト名またはサブジェクト代替名に、 ONTAPツールの IP アドレスにマッピングされた同じ FQDN が含まれている必要があります。


NOTE: CA 署名証明書から自己署名証明書に切り替えることはできません。

[role="tabbed-block"]
====
.ONTAPツール証明書のアップグレード
--
ONTAPツール タブには、証明書の種類 (自己署名/CA 署名) やドメイン名などの詳細が表示されます。展開中に、自己署名証明書がデフォルトで生成されます。証明書を更新したり、CA に証明書をアップグレードしたりできます。

.手順
. Web ブラウザからONTAPツール マネージャを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者認証情報を使用してログインします。
. 証明書を更新するには、[証明書] > [ONTAPツール] > [更新] を選択します。
+
証明書の有効期限が切れている場合、または有効期限が近づいている場合は、証明書を更新できます。更新オプションは、証明書の種類が CA 署名の場合に使用できます。ポップアップ ウィンドウで、サーバー証明書、秘密キー、ルート CA、中間証明書の詳細を入力します。

+

NOTE: 証明書が更新されるまでシステムはオフラインになり、 ONTAP Tools Manager インターフェイスからログアウトされます。

. 自己署名証明書をカスタム CA 証明書にアップグレードするには、[*証明書*] > [* ONTAPツール*] > [*CA にアップグレード*] オプションを選択します。
+
.. ポップアップ ウィンドウで、サーバー証明書、サーバー証明書の秘密キー、ルート CA 証明書、および中間証明書ファイルをアップロードします。
.. この証明書を生成したドメイン名を入力し、証明書をアップグレードします。
+

NOTE: アップグレードが完了するまでシステムはオフラインになり、 ONTAP Tools Manager インターフェイスからログアウトされます。





--
.VASAプロバイダー証明書のアップグレード
--
ONTAP tools for VMware vSphereは、 VASA プロバイダーの自己署名証明書を使用して導入されます。これにより、 vVolsデータストアに対して 1 つの vCenter Server インスタンスのみを管理できるようになります。複数の vCenter Server インスタンスを管理し、それらでvVols機能を有効にする場合は、自己署名証明書をカスタム CA 証明書に変更する必要があります。

.手順
. Web ブラウザからONTAPツール マネージャを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者認証情報を使用してログインします。
. 証明書を更新するには、[証明書] > [VASA プロバイダー] または [ONTAPツール] > [更新] を選択します。
. 自己署名証明書をカスタム CA 証明書にアップグレードするには、[証明書] > [VASA プロバイダー] または [ONTAPツール] > [CA にアップグレード] を選択します。
+
.. ポップアップ ウィンドウで、サーバー証明書、サーバー証明書の秘密キー、ルート CA 証明書、および中間証明書ファイルをアップロードします。
.. この証明書を生成したドメイン名を入力し、証明書をアップグレードします。
+

NOTE: アップグレードが完了するまでシステムはオフラインになり、 ONTAP Tools Manager インターフェイスからログアウトされます。





--
====