---
permalink: manage/collect-the-log-files.html 
sidebar: sidebar 
keywords:  
summary: 'ONTAP tools for VMware vSphere のグラフィカル ユーザー インターフェイス (GUI) で使用可能なオプションから、 ONTAP tools for VMware vSphereのログ ファイルを収集できます。テクニカル サポートに問題のトラブルシューティングを依頼すると、ログ ファイルの収集を求められることがあります。' 
---
= ログ ファイルの収集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPツール マネージャ ユーザー インターフェイスで使用可能なオプションから、 ONTAP tools for VMware vSphereのログ ファイルを収集できます。テクニカル サポートに問題のトラブルシューティングを依頼すると、ログ ファイルの収集を求められることがあります。


NOTE: ONTAPツール マネージャからログを生成すると、すべての vCenter Server インスタンスのすべてのログが含まれます。  vCenter クライアント ユーザー インターフェイスから生成されるログの範囲は、選択した vCenter Server に限定されます。

.手順
. Web ブラウザからONTAPツール マネージャを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者認証情報を使用してログインします。
. サイドバーから*ログバンドル*を選択します。
+
この処理には数分かかることがあります。

. ログ ファイルを生成するには、[*生成*] を選択します。
. ログ バンドルのラベルを入力し、[生成] を選択します。
+
tar.gz ファイルをダウンロードし、テクニカル サポートに送信します。



vCenter クライアント ユーザー インターフェイスを使用してログ バンドルを生成するには、次の手順に従います。

.手順
. vSphere クライアントにログインします。
. vSphere Client のホームページから、*サポート* > *ログ バンドル* > *生成* に移動します。
. ログバンドルのラベルを指定して、ログバンドルを生成します。ファイルが生成されると、ダウンロードオプションが表示されます。ダウンロードには時間がかかる場合があります。



NOTE: 生成されたログ バンドルは、過去 3 日間または 72 時間以内に生成されたログ バンドルに置き換えられます。
