---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: データストアの削除アクションはデータストアを削除します。  NFS または VMFS データストアの場合、データストアを使用している VM のリストを含むダイアログ ボックスが表示されます。 
---
= データストアを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データストアからストレージを削除するアクションは、vCenter Server 内の VMware vSphere によって検出または管理されているvVolsデータストアのONTAP tools for VMware vSphereでサポートされています。このアクションにより、 vVolsデータストアからボリュームを削除できます。

特定のボリュームにvVolsが存在する場合、削除オプションは無効になります。データストアからボリュームを削除するだけでなく、 ONTAPストレージ上の選択したボリュームを削除することもできます。

vCenter Server のONTAP tools for VMware vSphereからデータストアを削除するタスクは、次の操作を実行します。

* vVolコンテナをアンマウントする。
* igroup をクリーンアップします。igroupが使用されていない場合は、iqnをigroupから削除する。
* vVolコンテナを削除する。
* FlexVolはストレージ アレイに残す。


vCenter Server のONTAPツールから NFS、VMFS、または vVOL データストアを削除するには、次の手順に従います。

.手順
. vSphere クライアントにログインします。
. ホスト システム、ホスト クラスタ、またはデータ センターを右クリックし、* NetApp ONTAPツール* > * データストアの削除* を選択します。
+

NOTE: そのデータストアを使用している仮想マシンがある場合、そのデータストアを削除することはできません。データストアを削除する前に、仮想マシンを別のデータストアに移動する必要があります。データストアが保護されたホスト クラスターに属している場合は、ボリューム削除チェックボックスを選択できません。

+
.. NFS または VMFS データストアの場合、データストアを使用している VM のリストを含むダイアログ ボックスが表示されます。
.. VMFS データストアがASA r2 システム上に作成され、保護の一部である場合は、削除する前にデータストアの保護を解除する必要があります。
.. vVolsデータストアの場合、データストアの削除アクションでは、それに関連付けられたvVolsがない場合にのみデータストアが削除されます。データストアの削除ダイアログ ボックスには、 ONTAPクラスタからボリュームを削除するオプションがあります。
.. ASA r2 システム ベースのvVolsデータストアの場合、バックアップ ボリュームを削除するチェック ボックスは適用されません。


. ONTAPストレージ上のバックアップ ボリュームを削除するには、* ONTAPクラスター上のボリュームの削除* を選択します。
+

NOTE: 保護されたホスト クラスタの一部である VMFS データストアのONTAPクラスタ上のボリュームを削除することはできません。


