---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords:  
summary: ONTAP Tools Manager を使用して管理者パスワードを変更できます。 
---
= ONTAP tools for VMware vSphereを変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPツール マネージャーを使用して、 ONTAP tools for VMware vSphereをスケールアップし、展開内のノードの数を増やしたり、構成を高可用性 (HA) セットアップに変更したりします。  ONTAP tools for VMware vSphereは、最初は単一ノードの非 HA 構成で導入されます。


NOTE: 非 HA バックアップが有効になっているときに HA に移行するには、まずバックアップを無効にし、移行後に再度有効にします。

.開始する前に
* OVA テンプレートの OVA バージョンがノード 1 と同じであることを確認します。ノード 1 は、ONTAP tools for VMware vSphereが最初に導入されるデフォルト ノードです。
* CPU ホット アドとメモリ ホット プラグが有効になっていることを確認します。
* vCenter Server で、Disaster Recovery Service (DRS) の自動化レベルを部分的に自動化に設定します。  HA を展開した後、完全に自動化された状態に戻します。
* HA セットアップ内のノード ホスト名は小文字にする必要があります。


.手順
. Web ブラウザからONTAPツール マネージャを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者認証情報を使用してログインします。
. 概要セクションで*アプライアンス設定の編集*を選択します。
. *構成*セクションでは、スケールアップしてノード サイズを増やし、要件に応じて HA 構成を有効にすることができます。変更を行うには、vCenter Server の認証情報が必要です。
+
ONTAPツールが HA 構成の場合、コンテンツ ライブラリの詳細を変更できます。新しい編集を送信するには、パスワードを再度入力する必要があります。

+

NOTE: ONTAP tools for VMware vSphereでは、ノード サイズを増やすことしかできず、ノード サイズを縮小することはできません。HA 以外のセットアップでは、中規模の構成のみがサポートされます。HA セットアップでは、中規模および大規模の構成がサポートされます。

. HA トグル ボタンを使用して HA 構成を有効にします。  *HA 設定* ページで、次の点を確認します。
+
** コンテンツライブラリは、 ONTAPツールノードVMが実行されるvCenter Serverと同じvCenter Serverに属します。vCenter Serverの認証情報は、アプライアンスの変更に必要なOVAテンプレートの検証とダウンロードに使用されます。
** ONTAPツールをホストする仮想マシンは、ESXi ホストに直接展開されません。  VM はクラスターまたはリソース プールにデプロイする必要があります。
+

NOTE: HA 構成を有効にした後は、非 HA 単一ノード構成に戻すことはできません。



. *アプライアンス設定の編集* ウィンドウの *HA 設定* セクションで、ノード 2 と 3 の詳細を入力できます。  ONTAP tools for VMware vSphereは、 HA セットアップで 3 つのノードをサポートします。
+

NOTE: ワークフローを容易にするために、ほとんどの入力オプションにはノード 1 ネットワークの詳細が事前に入力されています。ただし、ウィザードの最終ページに進む前に入力データを編集することはできます。ONTAPツール管理ノードで IPv6 アドレスが有効になっている場合にのみ、他の 2 つのノードの IPv6 アドレスの詳細を入力できます。

+
ESXi ホストにONTAPツール VM が 1 つだけ含まれていることを確認します。次のウィンドウに移動するたびに入力が検証されます。

. *概要* セクションの詳細を確認し、変更を *保存* します。


.次の手順
*概要* ページには、デプロイメントのステータスが表示されます。ジョブ ID を使用すると、ジョブ ビューからアプライアンス設定編集ジョブのステータスを追跡することもできます。

HA の展開が失敗し、新しいノードのステータスが「新規」と表示される場合は、HA の有効化操作を再試行する前に、vCenter で新しい VM を削除します。

左側のパネルの *アラート* タブには、ONTAP tools for VMware vSphereのアラートが一覧表示されます。
