---
permalink: manage/edit-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 保護されたホスト クラスターのSnapMirror関係を編集できます。関係を追加、変更、削除できます。ただし、整合性グループ名を編集することはできません。 
---
= 保護されたホスト クラスターを変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
変更保護の一部として次のタスクを実行できます。すべての変更を同じワークフローで実行できます。

* 保護されたクラスターに新しいデータストアまたはホストを追加します。
* 保護設定に新しいSnapMirror関係を追加します。
* 保護設定から既存のSnapMirror関係を削除します。
* 既存のSnapMirror関係を変更します。




== ホストクラスタ保護の監視

ホスト クラスター保護の状態を監視するには、この手順を使用します。保護されているすべてのホスト クラスタを、その保護状態、 SnapMirror関係、データストア、および対応するSnapMirrorステータスとともに監視できます。

.手順
. vSphere クライアントにログインします。
. * NetApp ONTAPツール* > *保護* > *ホスト クラスター リレーションシップ* に移動します。
+
保護列の下のアイコンは保護の状態を示します

. アイコンの上にマウスを移動すると詳細が表示されます。




== 新しいデータストアまたはホストを追加する

新しく追加されたデータストアまたはホストを保護するには、この手順を使用します。  vCenter ネイティブ ユーザー インターフェイスを使用して、保護されたクラスタに新しいホストを追加したり、ホスト クラスタ上に新しいデータストアを作成したりできます。

.手順
. vSphere クライアントにログインします。
. 保護されたクラスタのプロパティを編集するには、次のいずれかを実行します。
+
.. * NetApp ONTAPツール* > *保護* > *ホストクラスタ関係*に移動し、クラスタの省略記号メニューを選択して*編集*を選択するか、
.. ホスト クラスターを右クリックし、* NetApp ONTAPツール* > *クラスターの保護* を選択します。


. vCenter ネイティブ ユーザー インターフェイスでデータストアを作成した場合、そのデータストアは保護されていないものとして表示されます。ユーザー インターフェイスでは、クラスター内のすべてのデータストアとその保護ステータスがダイアログ ボックスに表示されます。完全な保護を有効にするには、[保護] ボタンを選択します。
. 新しい ESXi ホストを追加した場合、保護ステータスは部分的に保護されていると表示されます。SnapMirror設定の下の省略記号メニューを選択し、[編集] を選択して、新しく追加された ESXi ホストの近接性を設定します。
+

NOTE: 非同期タイプの関係の場合、第3サイトのターゲットSVMを同じONTAPツールインスタンスに追加できないため、編集操作はサポートされません。ただし、ターゲットSVMのシステムマネージャまたはCLIを使用して、関係の設定を変更することは可能です。

. 必要な変更を行った後、[*保存*] を選択します。
. *Protect Cluster* ウィンドウで変更を確認できます。


vCenter タスクが作成され、*最近のタスク* パネルで進行状況を追跡できます。



== 新しいSnapMirror関係を追加する

.手順
. vSphere クライアントにログインします。
. 保護されたクラスタのプロパティを編集するには、次のいずれかを実行します。
+
.. * NetApp ONTAPツール* > *保護* > *ホストクラスタ関係*に移動し、クラスタの省略記号メニューを選択して*編集*を選択するか、
.. ホスト クラスターを右クリックし、* NetApp ONTAPツール* > *クラスターの保護* を選択します。


. *関係を追加*を選択します。
. 新しい関係を *Asynchronous* または *AutomatedFailOverDuplex* ポリシー タイプとして追加します。
. *保護*を選択します。
+
*Protect Cluster* ウィンドウで変更を確認できます。



vCenter タスクが作成され、*最近のタスク* パネルで進行状況を追跡できます。



== 既存のSnapMirror関係を削除する

非同期SnapMirror関係を削除するには、セカンダリ サイトの SVM またはクラスターを ONTAP tools for VMware vSphereのストレージ バックエンドとして追加する必要があります。すべてのSnapMirror関係を削除することはできません。関係を削除すると、 ONTAPクラスタ上のそれぞれの関係も削除されます。  AutomatedFailOverDuplex SnapMirror関係を削除すると、宛先のデータストアがマップ解除され、整合性グループ、LUN、ボリューム、および igroup が宛先ONTAPクラスタから削除されます。

関係を削除すると、セカンダリ サイトで再スキャンがトリガーされ、マップされていない LUN がホストからアクティブ パスとして削除されます。

.手順
. vSphere クライアントにログインします。
. 保護されたクラスタのプロパティを編集するには、次のいずれかを実行します。
+
.. * NetApp ONTAPツール* > *保護* > *ホストクラスタ関係*に移動し、クラスタの省略記号メニューを選択して*編集*を選択するか、
.. ホスト クラスターを右クリックし、* NetApp ONTAPツール* > *クラスターの保護* を選択します。


. SnapMirror設定の下の省略記号メニューを選択し、[削除] を選択します。


vCenter タスクが作成され、*最近のタスク* パネルで進行状況を追跡できます。



== 既存のSnapMirror関係を変更する

非同期SnapMirror関係を変更するには、セカンダリ サイトの SVM またはクラスターを ONTAP tools for VMware vSphereのストレージ バックエンドとして追加する必要があります。  AutomatedFailOverDuplex SnapMirror関係の場合、均一構成の場合はホストの近接性を、非均一構成の場合はホスト アクセスを変更できます。 Asynchronous と AutomatedFailOverDuplex のポリシー タイプを交換することはできません。クラスター上で新しく検出されたホストの近接性またはアクセスを設定できます。


NOTE: 既存の非同期SnapMirror関係を編集することはできません。

.手順
. vSphere クライアントにログインします。
. 保護されたクラスタのプロパティを編集するには、次のいずれかを実行します。
+
.. * NetApp ONTAPツール* > *保護* > *ホストクラスタ関係*に移動し、クラスタの省略記号メニューを選択して*編集*を選択するか、
.. ホスト クラスターを右クリックし、* NetApp ONTAPツール* > *クラスターの保護* を選択します。


. AutomatedFailOverDuplex ポリシー タイプを選択した場合は、ホストの近接性またはホスト アクセスの詳細を追加します。
. *保護*ボタンを選択します。


vCenter タスクが作成され、*最近のタスク* パネルで進行状況を追跡できます。
