---
permalink: manage/enable-backup.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphere以降、アプライアンスは動的ストレージ プロビジョナーを使用するため、ゼロ RPO を実現することはできません。ただし、RPO をほぼゼロにすることは可能です。 
---
= ONTAPツールのセットアップのバックアップを作成し、復元する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere以降、アプライアンスは動的ストレージ プロビジョナーを使用するため、ゼロ RPO を実現することはできません。ただし、RPO をほぼゼロにすることは可能です。ほぼゼロの RPO を実現するには、セットアップのバックアップを作成し、新しい仮想マシンに復元する必要があります。


NOTE: 非 HA バックアップが有効になっているときに HA に移行するには、まずバックアップを無効にし、移行後に再度有効にします。



== バックアップを作成し、バックアップファイルをダウンロードする

.手順
. vCenter Server からメンテナンス コンソールを開きます。
. メンテナンス ユーザとしてログインします。
. 入力 `4`*サポートと診断*を選択します。
. 入力 `3`*システムバックアップを有効にする*オプションを選択します。
. HA 以外の場合は、 ONTAPツール仮想マシンがデプロイされている vCenter の認証情報を入力します。
. バックアップ頻度の値を 5 ～ 60 分の範囲で入力します。
. Enterキーを押します
+
これにより、バックアップが作成され、定期的に仮想マシンのデータストアにバックアップがプッシュされます。

. バックアップにアクセスするには、ストレージセクションに移動し、仮想マシンのデータストアを選択します。
. *ファイル*セクションを選択します。
+
ファイルセクションではディレクトリを確認できます。ディレクトリの名前は、ドット (.) がアンダースコアに置き換えられ、末尾に _backup_ が付けられたONTAPツールの IP アドレスになります。

. バックアップの詳細については、[ファイル] > [ダウンロード] から backup_info.txt ファイルをダウンロードしてください。




== リカバリ

セットアップを回復するには、既存の仮想マシンの電源をオフにし、最初の展開で使用された OVA を使用して新しい仮想マシンを展開します。

新しい仮想マシンには同じONTAPツール IP アドレスを使用する必要があり、有効なサービス、ノード サイズ、HA モードなどのシステム構成は初期展開と同じである必要があります。

バックアップ ファイルからセットアップを回復するには、次の手順を実行します。

. vCenter Server からメンテナンス コンソールを開きます。
. メンテナンス ユーザとしてログインします。
. 入力 `4`*サポートと診断*を選択します。
. 入力 `2`*リモート診断アクセスを有効にする*オプションを選択し、診断アクセス用の新しいパスワードを作成します。
. ダウンロードしたディレクトリから任意のバックアップを 1 つ選択します。最新のバックアップ ファイル名は _backup_info.txt_ ファイルに記録されます。
. 以下のコマンドを実行してバックアップを新しい仮想マシンにコピーし、プロンプトが表示されたら診断パスワードを入力します。
+
[listing]
----
scp <Backup_X.tar.enc> diag@<node_ip>:/home/diag/system_recovery.tar.enc
----
+

NOTE: コマンドに記載されている宛先パスとファイル名 (/home/diag/system_recovery.tar.enc) を変更しないでください。

. バックアップ ファイルがコピーされたら、診断シェルにログインして次のコマンドを実行します。
+
[listing]
----
sudo perl /home/maint/scripts/post-deploy-upgrade.pl -recovery
----
+
ログは _/var/log/post-deploy-upgrade.log_ ファイルに記録されます。

. リカバリが成功すると、サービスと vCenter オブジェクトが復元されます。

