---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: データセンター内の既存の仮想マシンを移行する際には、いくつかの考慮事項に注意する必要があります。 
---
= 仮想マシンの移行またはクローン作成に関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データセンター内の既存の仮想マシンを移行する際には、いくつかの考慮事項に注意する必要があります。



== 保護されている仮想マシンの移行

保護されている仮想マシンは次の場所に移行できます。

* 別のESXiホストにある同じvVolデータストア
* 同じESXiホストにある、互換性のある別のvVolデータストア
* 別のESXiホストにある、互換性のある別のvVolデータストア


仮想マシンが別のFlexVol volumeに移行されると、それぞれのメタデータ ファイルも仮想マシン情報で更新されます。仮想マシンが同じストレージ内の別の ESXi ホストに移行された場合、基盤となるFlexVol volumeメタデータ ファイルは変更されません。



== 保護されている仮想マシンのクローニング

保護されている仮想マシンは、次の場所にクローニングできます。

* レプリケーション グループを使用する同じFlexVolの同じコンテナ
+
同じFlexVolのメタデータ ファイルが、クローニングされた仮想マシンの詳細で更新されます。

* レプリケーション グループを使用している別のFlexVolの同じコンテナ
+
クローニングされた仮想マシンが配置されているFlexVolのメタデータ ファイルが、クローニングされた仮想マシンの詳細で更新されます。

* 別のコンテナまたはvVolデータストア
+
クローニングされた仮想マシンが配置されているFlexVolのメタデータ ファイルが仮想マシンの詳細で更新されます。



VMware は現在、VM テンプレートにクローンされた仮想マシンをサポートしていません。

保護されている仮想マシンのクローンのクローニングはサポートされています。

参照 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["クローン用の仮想マシンの作成"]詳細についてはこちらをご覧ください。



== 仮想マシンのSnapshot

現時点では、メモリなしの仮想マシンSnapshotのみがサポートされています。仮想マシンにメモリありのSnapshotが存在する場合、仮想マシンは保護対象とはみなされません。

また、メモリ スナップショットを持つ保護されていない仮想マシンを保護することもできません。このリリースでは、仮想マシンの保護を有効にする前に、メモリありのSnapshotを削除する必要があります。

ASA r2 ストレージ タイプを備えた Windows VM の場合、仮想マシンのスナップショットを作成すると、読み取り専用のスナップショットになります。 VM の電源オン要求があると、VASA プロバイダーは読み取り専用スナップショットを使用して LUN を作成し、IOPS を有効にします。電源オフ要求時に、VASA プロバイダーは作成された LUN を削除し、IOPS を無効にします。
