---
permalink: manage/mount-datastores-on-host.html 
sidebar: sidebar 
keywords:  
summary: 追加のホストにデータストアをマウントすると、そのホストからストレージにアクセスできるようになります。ホストをVMware環境に追加したあとで、そのホストにデータストアをマウントできます。 
---
= NFSおよびVMFSデータストアをマウントする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
追加のホストにデータストアをマウントすると、そのホストからストレージにアクセスできるようになります。ホストをVMware環境に追加したあとで、そのホストにデータストアをマウントできます。


NOTE: 新しいESXiホストを追加する場合、 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/use-quickstart-to-add---host-to-a-cluster.html["vSphere クラスタに ESX ホストを追加するワークフロー"]スケジュールされたホスト検出が完了するまで待機してから、 ONTAPツールに表示されます。あるいは、 NetApp ONTAPツールの概要画面から手動で検出を実行することもできます。

.タスク概要
* vSphere クライアントのバージョンと選択したデータストアのタイプによっては、一部の右クリック アクションが無効になったり使用できなくなったりします。
+
** vSphere クライアント 8.0 以降のバージョンを使用している場合、右クリック オプションの一部は非表示になります。
** vSphere 7.0U3 から vSphere 8.0 バージョンでは、オプションは表示されますが、アクションは無効になります。


* ホスト クラスターが均一な構成で保護されている場合、データストアのマウント オプションは無効になります。


.手順
. vSphere Client のホームページから、[ホストとクラスタ] を選択します。
. 左側のナビゲーション ペインで、ホストが含まれているデータ センターを選択します。
. NFS/VMFS データストアをホストまたはホスト クラスタにマウントするには、右クリックして * NetApp ONTAPツール* > * データストアのマウント* を選択します。
. マウントするデータストアを選択し、「マウント」を選択します。


.次の手順
最近のタスク パネルで進行状況を追跡できます。

.関連トピック
link:../manage/add-vsphere-host.html["新しい VMware vSphere ホストを追加する"]
