---
permalink: manage/storage-backend.html 
sidebar: sidebar 
keywords:  
summary: ストレージ バックエンドは、ESXi ホストがデータ ストレージに使用するシステムです。 
---
= ストレージバックエンドの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ バックエンドは、ESXi ホストがデータ ストレージに使用するシステムです。



== ストレージを発見

スケジュールされた検出によってストレージの詳細が更新されるのを待たずに、ストレージ バックエンドの検出をオンデマンドで実行できます。

ストレージ バックエンドを検出するには、以下の手順に従います。

.手順
. vSphere クライアントにログインします。
. ショートカット ページで、プラグイン セクションの * NetApp ONTAPツール* を選択します。
. ONTAPツールの左側のペインで、*ストレージ バックエンド* に移動し、ストレージ バックエンドを選択します。
. 縦の省略記号メニューを選択し、「ストレージの検出」を選択します。


最近のタスク パネルで進行状況を追跡できます。



== ストレージバックエンドを変更する

ストレージ バックエンドを変更するには、このセクションの手順に従います。

. vSphere クライアントにログインします。
. ショートカット ページで、プラグイン セクションの * NetApp ONTAPツール* を選択します。
. ONTAPツールの左側のペインで、*ストレージ バックエンド* に移動し、ストレージ バックエンドを選択します。
. 縦の省略記号メニューを選択し、[*変更*] を選択して資格情報またはポート名を変更します。最近のタスク パネルで進行状況を追跡できます。


次の手順に従って、 ONTAPツール マネージャを使用してグローバルONTAPクラスタの変更操作を実行できます。

. Web ブラウザからONTAPツール マネージャを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者認証情報を使用してログインします。
. サイドバーからストレージ バックエンドを選択します。
. 変更するストレージ バックエンドを選択します。
. 縦の省略記号メニューを選択し、[変更] を選択します。
. 資格情報またはポートを変更できます。ストレージ バックエンドを変更するには、*ユーザー名* と *パスワード* を入力します。




== ストレージバックエンドを削除する

ストレージ バックエンドを削除する前に、ストレージ バックエンドに接続されているすべてのデータストアを削除する必要があります。ストレージ バックエンドを削除するには、以下の手順に従います。

. vSphere クライアントにログインします。
. ショートカット ページで、プラグイン セクションの * NetApp ONTAPツール* を選択します。
. ONTAPツールの左側のペインで、*ストレージ バックエンド* に移動し、ストレージ バックエンドを選択します。
. 縦の省略記号メニューを選択し、[削除] を選択します。ストレージ バックエンドにデータストアが含まれていないことを確認します。最近のタスク パネルで進行状況を追跡できます。


ONTAPツール マネージャを使用して、グローバルONTAPクラスタの削除操作を実行できます。

. Web ブラウザからONTAPツール マネージャを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者認証情報を使用してログインします。
. サイドバーから*ストレージ バックエンド*を選択します。
. 削除するストレージバックエンドを選択します
. 縦の省略記号メニューを選択し、[削除] を選択します。




== ストレージバックエンドのドリルダウンビュー

ストレージ バックエンド ページには、すべてのストレージ バックエンドが一覧表示されます。ストレージの検出、変更、および削除の操作は、クラスタの下の個々の子 SVM ではなく、追加したストレージ バックエンドに対して実行できます。

ストレージ バックエンドの下の親クラスターまたは子クラスターのいずれかを選択すると、コンポーネントの全体的な概要が表示されます。親クラスターを選択すると、アクション ドロップダウンが表示され、そこからストレージの検出、変更、削除の操作を実行できます。

概要ページには次の詳細が表示されます。

* ストレージバックエンドのステータス
* 容量情報
* VMに関する基本情報
* ネットワークの IP アドレスやポートなどのネットワーク情報。子 SVM の場合、情報は親ストレージ バックエンドと同じになります。
* ストレージ バックエンドに対して許可および制限されるPrivileges。子 SVM の場合、情報は親ストレージ バックエンドと同じになります。Privilegesは、クラスターベースのストレージ バックエンドにのみ表示されます。  SVM をストレージ バックエンドとして追加すると、権限情報は表示されません。
* SVM またはクラスタの分離プロパティが「true」に設定されている場合、 ASA r2 システム クラスタのドリルダウン ビューにはローカル層タブが含まれません。
* ASA r2 SVM システムの場合、容量ポートレットは表示されません。容量ポータルは、SVM またはクラスターの disaggregated プロパティが「true」に設定されている場合にのみ必要です。
* ASA r2 SVM システムの場合、基本情報セクションにプラットフォーム タイプが表示されます。


インターフェース タブには、インターフェースに関する詳細情報が表示されます。

ローカル ティア タブには、集計リストに関する詳細情報が表示されます。
